-- 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량을 출력
-- OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL 로 표시
-- 판매일 오름차순 정렬, 상품 ID 오름차순, 유저 ID 오름차순 정렬

SELECT
    DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,
    PRODUCT_ID,
    USER_ID, 
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '%2022-03%'
GROUP BY USER_ID, PRODUCT_ID, SALES_DATE
UNION ALL
SELECT
    DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,
    PRODUCT_ID,
    NULL,
    SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '%2022-03%'
GROUP BY PRODUCT_ID, SALES_DATE
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;