-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액
-- 대여 금액을 기준 내림차순 > 자동차 종류를 기준 오름차순 > 자동차 ID를 기준으로 내림차순 정렬
SELECT 
    c.CAR_ID,
    c.CAR_TYPE,
    FLOOR((c.DAILY_FEE*30) * (1-(dp.DISCOUNT_RATE/100))) FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN (
    SELECT CAR_ID, MIN(START_DATE) START_DATE, MAX(END_DATE) END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
    GROUP BY CAR_ID
) rh
ON c.CAR_ID = rh.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
ON c.CAR_TYPE = dp.CAR_TYPE
AND dp.DURATION_TYPE LIKE '30%'
AND c.CAR_TYPE IN ('세단','SUV')
AND ('2022-11-01' > rh.END_DATE OR '2022-11-30' < rh.START_DATE)
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;



-- CAR_RENTAL_COMPANY_CAR 의 DAILY_FEE 칼럼 할인 가격 계산
# SELECT FLOOR(c.DAILY_FEE*(1-(dp.DISCOUNT_RATE/100)))
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
# INNER JOIN CAR_RENTAL_COMPANY_CAR c
# ON dp.CAR_TYPE = c.CAR_TYPE
# WHERE dp.CAR_TYPE IN ('세단','SUV') AND dp.DURATION_TYPE LIKE '30%';