-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계
SELECT  
    YEAR(os.SALES_DATE) YEAR, 
    MONTH(os.SALES_DATE) MONTH,
    ui.GENDER,
    COUNT(DISTINCT ui.USER_ID) USERS
FROM USER_INFO ui
INNER JOIN ONLINE_SALE os
ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, ui.GENDER
ORDER BY YEAR, MONTH, ui.GENDER;

-- 날짜 변형
# SELECT
#     DATE_FORMAT(SALES_DATE,'%Y') YEAR, 
#     REPLACE(RIGHT(DATE_FORMAT(SALES_DATE,'%Y-%m'),2),0,'') MONTH
# FROM ONLINE_SALE
# GROUP BY MONTH;

-- 집계
# SELECT 
#     DATE_FORMAT(SALES_DATE,'%Y-%m'),
#     COUNT(*)
# FROM ONLINE_SALE
# GROUP BY DATE_FORMAT(SALES_DATE,'%Y-%m');