-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 카테고리(CATEGORY), 총 판매량(TOTAL_SALES)

SELECT b.CATEGORY
    ,SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK b
INNER JOIN BOOK_SALES bs
ON b.BOOK_ID = bs.BOOK_ID
WHERE TO_CHAR(bs.SALES_DATE, 'YYYYMM') = 202201
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;

