-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회
-- 총매출 내림차순,식품 ID 오름차순
SELECT
    fp.PRODUCT_ID
    ,fp.PRODUCT_NAME
    ,SUM(fp.PRICE*fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER fo
INNER JOIN FOOD_PRODUCT fp
ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE fo.PRODUCE_DATE LIKE '2022-05%'
GROUP BY fp.PRODUCT_ID,fp.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC ,fp.PRODUCT_ID;
