-- 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회
# WITH RECURSIVE time_h AS (
#   SELECT 0 AS HOUR_DATA
#   UNION ALL
#   SELECT HOUR_DATA+1 
#     FROM time_h
#    WHERE HOUR_DATA < 23
# )
SELECT
    h.HOUR
    ,COUNT(DISTINCT ao.ANIMAL_ID) AS COUNT
FROM (
    SELECT ROW_NUMBER() OVER()-1 AS HOUR
    FROM ANIMAL_OUTS
    LIMIT 24
) h
LEFT JOIN ANIMAL_OUTS ao
ON h.HOUR = HOUR(ao.DATETIME)
GROUP BY h.HOUR
ORDER BY h.HOUR;