SELECT
    D.ID, D.EMAIL, D.FIRST_NAME,  D.LAST_NAME
FROM DEVELOPERS AS D
INNER JOIN SKILLCODES AS S
ON D.SKILL_CODE & S.CODE = S.CODE
WHERE S.CATEGORY = 'Front End'
GROUP BY  D.ID, D.EMAIL, D.FIRST_NAME,  D.LAST_NAME
ORDER BY D.ID;